# -*- coding: utf-8 -*-
"""Sample Media

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M5ReUN51FfUb01GdLMftXipg_3b7bM_u
"""

print("Write the first age", end=" ")
first = float(input())
print("Write the second age", end=" ")
second = float(input())
print("Write the third age", end=" ")
third = float(input())


sample_media = (first + second + third) / 3
print(f"The sample media is {sample_media}")